/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.app.form;

import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author GERFOR
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();

        this.setExtendedState(this.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu4 = new javax.swing.JMenu();
        dpnEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jM_CambioMenu = new javax.swing.JMenuItem();
        jM_Salir = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jM_CrearInventario = new javax.swing.JMenuItem();
        jM_CargaMasivaInventario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);

        dpnEscritorio.setBackground(new java.awt.Color(26, 179, 181));

        javax.swing.GroupLayout dpnEscritorioLayout = new javax.swing.GroupLayout(dpnEscritorio);
        dpnEscritorio.setLayout(dpnEscritorioLayout);
        dpnEscritorioLayout.setHorizontalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        dpnEscritorioLayout.setVerticalGroup(
            dpnEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu5.setText("Inicio");

        jM_CambioMenu.setText("Cambio de Usuario");
        jM_CambioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_CambioMenuActionPerformed(evt);
            }
        });
        jMenu5.add(jM_CambioMenu);

        jM_Salir.setText("Salir");
        jM_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_SalirActionPerformed(evt);
            }
        });
        jMenu5.add(jM_Salir);

        jMenuBar1.add(jMenu5);

        jMenu1.setText("Inventario");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jM_CrearInventario.setText("Crear");
        jM_CrearInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_CrearInventarioActionPerformed(evt);
            }
        });
        jMenu1.add(jM_CrearInventario);

        jM_CargaMasivaInventario.setText("Carga Masiva");
        jM_CargaMasivaInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jM_CargaMasivaInventarioActionPerformed(evt);
            }
        });
        jMenu1.add(jM_CargaMasivaInventario);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hojas de Vida");

        jMenuItem3.setText("Actualizar Vacaciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Actualización Masiva");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpnEscritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jM_CrearInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_CrearInventarioActionPerformed
//        try {
////            CargaManualUsuarios cmu = new CargaManualUsuarios();
//
//            dpnEscritorio.add(cmu);
//            cmu.setMaximum(true);
//            cmu.setVisible(true);
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jM_CrearInventarioActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        ActualizacionManualVacaciones cmv = new ActualizacionManualVacaciones();
//        dpnEscritorio.add(cmv);
//        try {
//            cmv.setMaximum(true);
//        } catch (PropertyVetoException ex) {
//            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        cmv.setVisible(true);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jM_CargaMasivaInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_CargaMasivaInventarioActionPerformed
//        CargaMasivaUsuario cmau = new CargaMasivaUsuario();
//        cmau.setLocationRelativeTo(null);
////        dpnEscritorio.add(cmau);
//        cmau.setVisible(true);
    }//GEN-LAST:event_jM_CargaMasivaInventarioActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
//        CargaMasivaVacaciones cmav = new CargaMasivaVacaciones();
//        cmav.setLocationRelativeTo(null);
////        dpnEscritorio.add(cmav);
//        cmav.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jM_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_SalirActionPerformed
        System.exit(0);
        setDefaultCloseOperation(Menu.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jM_SalirActionPerformed

    private void jM_CambioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jM_CambioMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jM_CambioMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane dpnEscritorio;
    private javax.swing.JMenuItem jM_CambioMenu;
    private javax.swing.JMenuItem jM_CargaMasivaInventario;
    private javax.swing.JMenuItem jM_CrearInventario;
    private javax.swing.JMenuItem jM_Salir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
